# Generated by Django 6.0.4 on 2026-05-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_seed_default_stages'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kanbanstage',
            table='concimed_etapa_kanban',
        ),
        migrations.AlterModelTable(
            name='lead',
            table='concimed_lead',
        ),
    ]
