# Generated by Django 6.0.4 on 2026-05-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_kanbanstage_table_alter_lead_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='owner',
        ),
        migrations.AddField(
            model_name='lead',
            name='owner_external_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='owner_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
