# Generated by Django 6.0.4 on 2026-05-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='concimed_usuario_perfil',
        ),
    ]
