# Generated by Django 6.0.4 on 2026-05-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
